# Generated by Django 3.1.4 on 2021-01-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_info',
            name='request_assigned',
        ),
        migrations.RemoveField(
            model_name='model_info',
            name='request_remark',
        ),
        migrations.RemoveField(
            model_name='model_info',
            name='request_status',
        ),
        migrations.CreateModel(
            name='model_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_remark', models.TextField(null=True)),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_info')),
                ('request_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_admin')),
                ('request_status', models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_status')),
            ],
        ),
    ]
